package eu.kanade.tachiyomi.source.online

import android.app.Application
import eu.kanade.tachiyomi.network.AndroidCookieJar
import eu.kanade.tachiyomi.network.NetworkHelper
import eu.kanade.tachiyomi.source.CatalogueSource
import exh.log.maybeInjectEHLogger
import exh.pref.DelegateSourcePreferences
import exh.source.DelegatedHttpSource
import okhttp3.Headers
import okhttp3.OkHttpClient
import uy.kohesive.injekt.Injekt
import uy.kohesive.injekt.api.get

/**
 * Identity and network layer of an [HttpSource]: id generation, headers, the OkHttp client and
 * the SY delegate hook. Split out of HttpSource so each concern stays under the file cap; the
 * class chain keeps every member reachable from [HttpSource] for compiled extensions.
 */
public abstract class HttpSourceBase : CatalogueSource {

    /**
     * Network service.
     */
    // SY -->
    protected val network: NetworkHelper by lazy {
        val network = Injekt.get<NetworkHelper>()
        object : NetworkHelper(Injekt.get<Application>(), Injekt.get(), network.isDebugBuild) {
            override val client: OkHttpClient
                get() = delegate?.networkHttpClient ?: network.client
                    .newBuilder()
                    .maybeInjectEHLogger()
                    .build()

            @Deprecated("The regular client handles Cloudflare by default")
            override val cloudflareClient: OkHttpClient
                get() = delegate?.networkHttpClient ?: client

            override val cookieJar: AndroidCookieJar
                get() = network.cookieJar
        }
    }
    // SY <--

    /**
     * Base url of the website without the trailing slash, like: http://mysite.com
     */
    public abstract val baseUrl: String

    /**
     * Version id used to generate the source id. If the site completely changes and urls are
     * incompatible, you may increase this value and it'll be considered as a new source.
     */
    public open val versionId: Int = 1

    /**
     * ID of the source. By default it uses a generated id using the first 16 characters (64 bits)
     * of the MD5 of the string `"${name.lowercase()}/$lang/$versionId"`.
     *
     * The ID is generated by the [generateId] function, which can be reused if needed
     * to generate outdated IDs for cases where the source name or language needs to
     * be changed but migrations can be avoided.
     *
     * Note: the generated ID sets the sign bit to `0`.
     */
    override val id: Long by lazy { generateId(name, lang, versionId) }

    /**
     * Headers used for requests. Declared (lazily) on [HttpSource] itself, not here: see the
     * note on that override.
     */
    public abstract val headers: Headers

    /**
     * Default network client for doing requests.
     */
    public open val client: OkHttpClient
        // SY -->
        get() = delegate?.baseHttpClient ?: network.client
    // SY <--

    // EXH -->
    private var delegate: DelegatedHttpSource? = null
        get() = if (Injekt.get<DelegateSourcePreferences>().delegateSources.get()) {
            field
        } else {
            null
        }

    /**
     * Returns the base (home) URL of the website as a string.
     *
     * This is typically the root address that serves as the main entry point
     * to the site's content, such as "https://mihon.tech".
     *
     * This method is used in the browse screen to determine the URL
     * opened when tapping "Open in WebView".
     *
     * @return The website’s home page URL. Defaults to [baseUrl].
     */
    public open fun getHomeUrl(): String = baseUrl

    /**
     * Generates a unique ID for the source based on the provided [name], [lang] and
     * [versionId]. It will use the first 16 characters (64 bits) of the MD5 of the string
     * `"${name.lowercase()}/$lang/$versionId"`.
     *
     * Note: the generated ID sets the sign bit to `0`.
     *
     * Can be used to generate outdated IDs, such as when the source name or language
     * needs to be changed but migrations can be avoided.
     *
     * @since extensions-lib 1.5
     * @param name [String] the name of the source
     * @param lang [String] the language of the source
     * @param versionId [Int] the version ID of the source
     * @return a unique ID for the source
     */
    @Suppress("MemberVisibilityCanBePrivate")
    protected fun generateId(name: String, lang: String, versionId: Int): Long = sourceIdOf(name, lang, versionId)

    /**
     * Headers builder for requests. Implementations can override this method for custom headers.
     */
    protected open fun headersBuilder(): Headers.Builder = Headers.Builder().apply {
        add("User-Agent", network.defaultUserAgentProvider())
    }

    /**
     * Visible name of the source.
     */
    override fun toString(): String = "$name (${lang.uppercase()})"

    /** SY: routes this source's clients through [delegate] while delegated sources are enabled. */
    public fun bindDelegate(delegate: DelegatedHttpSource) {
        this.delegate = delegate
    }
    // EXH <--
}
