package eu.kanade.presentation.theme.colorscheme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

/**
 * Colors for Green Apple theme
 * Original color scheme by CarlosEsco, Jays2Kings and CrepeTF
 * M3 colors generated by Material Theme Builder (https://goo.gle/material-theme-builder-web).
 *
 * Key colors:
 * Primary #188140
 * Secondary #188140
 * Tertiary #D33131
 * Neutral #5D5F5B
 */
internal object GreenAppleColorScheme : BaseColorScheme() {

    override val darkScheme = darkColorScheme(
        primary = Color(color = 0xFF7ADB8F),
        onPrimary = Color(color = 0xFF003917),
        primaryContainer = Color(color = 0xFF017737),
        onPrimaryContainer = Color(color = 0xFFFFFFFF),
        secondary = Color(color = 0xFF7ADB8F), // Unread badge
        onSecondary = Color(color = 0xFF003917), // Unread badge text
        secondaryContainer = Color(color = 0xFF017737), // Navigation bar selector pill & progress indicator (remaining)
        onSecondaryContainer = Color(color = 0xFFFFFFFF), // Navigation bar selected icon
        tertiary = Color(color = 0xFFFFB3AC), // Downloaded badge
        onTertiary = Color(color = 0xFF680008), // Downloaded badge text
        tertiaryContainer = Color(color = 0xFFC7282A),
        onTertiaryContainer = Color(color = 0xFFFFFFFF),
        error = Color(color = 0xFFFFB4AB),
        onError = Color(color = 0xFF690005),
        errorContainer = Color(color = 0xFF93000A),
        onErrorContainer = Color(color = 0xFFFFDAD6),
        background = Color(color = 0xFF0F1510),
        onBackground = Color(color = 0xFFDFE4DB),
        surface = Color(color = 0xFF0F1510),
        onSurface = Color(color = 0xFFDFE4DB),
        surfaceVariant = Color(color = 0xFF3F493F), // Navigation bar background (ThemePrefWidget)
        onSurfaceVariant = Color(color = 0xFFBECABC),
        outline = Color(color = 0xFF889487),
        outlineVariant = Color(color = 0xFF3F493F),
        scrim = Color(color = 0xFF000000),
        inverseSurface = Color(color = 0xFFDFE4DB),
        inverseOnSurface = Color(color = 0xFF2C322C),
        inversePrimary = Color(color = 0xFF006D32),
        surfaceDim = Color(color = 0xFF0F1510),
        surfaceBright = Color(color = 0xFF353B35),
        surfaceContainerLowest = Color(color = 0xFF0A0F0B),
        surfaceContainerLow = Color(color = 0xFF181D18),
        surfaceContainer = Color(color = 0xFF1C211C), // Navigation bar background
        surfaceContainerHigh = Color(color = 0xFF262B26),
        surfaceContainerHighest = Color(color = 0xFF313630),
    )

    override val lightScheme = lightColorScheme(
        primary = Color(color = 0xFF005927),
        onPrimary = Color(color = 0xFFFFFFFF),
        primaryContainer = Color(color = 0xFF188140),
        onPrimaryContainer = Color(color = 0xFFFFFFFF),
        secondary = Color(color = 0xFF005927), // Unread badge
        onSecondary = Color(color = 0xFFFFFFFF), // Unread badge text
        secondaryContainer = Color(color = 0xFF97f7a9), // Navigation bar selector pill & progress indicator (remaining)
        onSecondaryContainer = Color(color = 0xFF000000), // Navigation bar selected icon
        tertiary = Color(color = 0xFF9D0012), // Downloaded badge
        onTertiary = Color(color = 0xFFFFFFFF), // Downloaded badge text
        tertiaryContainer = Color(color = 0xFFD33131),
        onTertiaryContainer = Color(color = 0xFFFFFFFF),
        error = Color(color = 0xFFBA1A1A),
        onError = Color(color = 0xFFFFFFFF),
        errorContainer = Color(color = 0xFFFFDAD6),
        onErrorContainer = Color(color = 0xFF410002),
        background = Color(color = 0xFFF6FBF2),
        onBackground = Color(color = 0xFF181D18),
        surface = Color(color = 0xFFF6FBF2),
        onSurface = Color(color = 0xFF181D18),
        surfaceVariant = Color(color = 0xFFDAE6D7), // Navigation bar background (ThemePrefWidget)
        onSurfaceVariant = Color(color = 0xFF3F493F),
        outline = Color(color = 0xFF6F7A6E),
        outlineVariant = Color(color = 0xFFBECABC),
        scrim = Color(color = 0xFF000000),
        inverseSurface = Color(color = 0xFF2C322C),
        inverseOnSurface = Color(color = 0xFFEDF2E9),
        inversePrimary = Color(color = 0xFF7ADB8F),
        surfaceDim = Color(color = 0xFFD6DCD3),
        surfaceBright = Color(color = 0xFFF6FBF2),
        surfaceContainerLowest = Color(color = 0xFFFFFFFF),
        surfaceContainerLow = Color(color = 0xFFF0F5EC),
        surfaceContainer = Color(color = 0xFFEAEFE6), // Navigation bar background
        surfaceContainerHigh = Color(color = 0xFFE4EAE1),
        surfaceContainerHighest = Color(color = 0xFFDFE4DB),
    )
}
