package eu.kanade.presentation.theme.colorscheme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

/**
 * Colors for Midnight Dusk theme
 * Original color scheme by CrepeTF
 * M3 color scheme generated by Material Theme Builder (https://goo.gle/material-theme-builder-web)
 *
 * Key colors:
 * Primary #F02475
 * Secondary #F02475
 * Tertiary #7A5733
 * Neutral #16151D
 */
internal object MidnightDuskColorScheme : BaseColorScheme() {

    override val darkScheme = darkColorScheme(
        primary = Color(color = 0xFFF02475),
        onPrimary = Color(color = 0xFFFFFFFF),
        primaryContainer = Color(color = 0xFFBD1C5C),
        onPrimaryContainer = Color(color = 0xFFFFFFFF),
        inversePrimary = Color(color = 0xFFF02475),
        secondary = Color(color = 0xFFF02475), // Unread badge
        onSecondary = Color(color = 0xFF16151D), // Unread badge text
        secondaryContainer = Color(color = 0xFF66183C), // Navigation bar selector pill & progress indicator (remaining)
        onSecondaryContainer = Color(color = 0xFFF02475), // Navigation bar selector icon
        tertiary = Color(color = 0xFF55971C), // Downloaded badge
        onTertiary = Color(color = 0xFF16151D), // Downloaded badge text
        tertiaryContainer = Color(color = 0xFF386412),
        onTertiaryContainer = Color(color = 0xFFE5E1E5),
        background = Color(color = 0xFF16151D),
        onBackground = Color(color = 0xFFE5E1E5),
        surface = Color(color = 0xFF16151D),
        onSurface = Color(color = 0xFFE5E1E5),
        surfaceVariant = Color(color = 0xFF281624), // Navigation bar background (ThemePrefWidget)
        onSurfaceVariant = Color(color = 0xFFD6C1C4),
        surfaceTint = Color(color = 0xFFF02475),
        inverseSurface = Color(color = 0xFF333043),
        inverseOnSurface = Color(color = 0xFFFFFFFF),
        outline = Color(color = 0xFF9F8C8F),
        surfaceContainerLowest = Color(color = 0xFF221320),
        surfaceContainerLow = Color(color = 0xFF251522),
        surfaceContainer = Color(color = 0xFF281624), // Navigation bar background
        surfaceContainerHigh = Color(color = 0xFF2D1C2A),
        surfaceContainerHighest = Color(color = 0xFF2F1F2C),
    )

    override val lightScheme = lightColorScheme(
        primary = Color(color = 0xFFBB0054),
        onPrimary = Color(color = 0xFFFFFFFF),
        primaryContainer = Color(color = 0xFFFFD9E1),
        onPrimaryContainer = Color(color = 0xFF3F0017),
        inversePrimary = Color(color = 0xFFFFB1C4),
        secondary = Color(color = 0xFFBB0054), // Unread badge
        onSecondary = Color(color = 0xFFFFFFFF), // Unread badge text
        secondaryContainer = Color(color = 0xFFEFBAD4), // Navigation bar selector pill & progress indicator (remaining)
        onSecondaryContainer = Color(color = 0xFFD1377C), // Navigation bar selector icon
        tertiary = Color(color = 0xFF006638), // Downloaded badge
        onTertiary = Color(color = 0xFFFFFFFF), // Downloaded badge text
        tertiaryContainer = Color(color = 0xFF00894b),
        onTertiaryContainer = Color(color = 0xFF2D1600),
        background = Color(color = 0xFFFFFBFF),
        onBackground = Color(color = 0xFF1C1B1F),
        surface = Color(color = 0xFFFFFBFF),
        onSurface = Color(color = 0xFF1C1B1F),
        surfaceVariant = Color(color = 0xFFF9E6F1), // Navigation bar background (ThemePrefWidget)
        onSurfaceVariant = Color(color = 0xFF524346),
        surfaceTint = Color(color = 0xFFBB0054),
        inverseSurface = Color(color = 0xFF313033),
        inverseOnSurface = Color(color = 0xFFF4F0F4),
        outline = Color(color = 0xFF847376),
        surfaceContainerLowest = Color(color = 0xFFDAC0CD),
        surfaceContainerLow = Color(color = 0xFFE8D1DD),
        surfaceContainer = Color(color = 0xFFF9E6F1), // Navigation bar background
        surfaceContainerHigh = Color(color = 0xFFFCF3F8),
        surfaceContainerHighest = Color(color = 0xFFFEF9FC),
    )
}
