package eu.kanade.presentation.theme.colorscheme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

internal object MonochromeColorScheme : BaseColorScheme() {

    override val darkScheme = darkColorScheme(
        primary = Color(color = 0xFFFFFFFF),
        onPrimary = Color(color = 0xFF000000),
        primaryContainer = Color(color = 0xFFFFFFFF),
        onPrimaryContainer = Color(color = 0xFF000000),
        secondary = Color(color = 0xFFFFFFFF),
        onSecondary = Color(color = 0xFF000000),
        secondaryContainer = Color(color = 0xFF777777),
        onSecondaryContainer = Color(color = 0xFF000000),
        tertiary = Color(color = 0xFF777777),
        onTertiary = Color(color = 0xFFFFFFFF),
        tertiaryContainer = Color(color = 0xFFFFFFFF),
        onTertiaryContainer = Color(color = 0xFF000000),
        error = Color(color = 0xFFFFFFFF),
        onError = Color(color = 0xFF000000),
        errorContainer = Color(color = 0xFFFFFFFF),
        onErrorContainer = Color(color = 0xFF000000),
        background = Color(color = 0xFF000000),
        onBackground = Color(color = 0xFFFFFFFF),
        surface = Color(color = 0xFF000000),
        onSurface = Color(color = 0xFFFFFFFF),
        surfaceVariant = Color(color = 0xFF000000),
        onSurfaceVariant = Color(color = 0xFFFFFFFF),
        outline = Color(color = 0xFFFFFFFF),
        outlineVariant = Color(color = 0xFFFFFFFF),
        scrim = Color(color = 0xFF000000),
        inverseSurface = Color(color = 0xFFFFFFFF),
        inverseOnSurface = Color(color = 0xFF000000),
        inversePrimary = Color(color = 0xFF000000),
        surfaceDim = Color(color = 0xFF000000),
        surfaceBright = Color(color = 0xFFFFFFFF),
        surfaceContainerLowest = Color(color = 0xFF000000),
        surfaceContainerLow = Color(color = 0xFF000000),
        surfaceContainer = Color(color = 0xFF000000),
        surfaceContainerHigh = Color(color = 0xFF000000),
        surfaceContainerHighest = Color(color = 0xFF000000),
    )

    override val lightScheme = lightColorScheme(
        primary = Color(color = 0xFF000000),
        onPrimary = Color(color = 0xFFFFFFFF),
        primaryContainer = Color(color = 0xFF000000),
        onPrimaryContainer = Color(color = 0xFFFFFFFF),
        secondary = Color(color = 0xFF000000),
        onSecondary = Color(color = 0xFFFFFFFF),
        secondaryContainer = Color(color = 0xFF888888),
        onSecondaryContainer = Color(color = 0xFFFFFFFF),
        tertiary = Color(color = 0xFF888888),
        onTertiary = Color(color = 0xFFFFFFFF),
        tertiaryContainer = Color(color = 0xFF000000),
        onTertiaryContainer = Color(color = 0xFFFFFFFF),
        error = Color(color = 0xFF000000),
        onError = Color(color = 0xFFFFFFFF),
        errorContainer = Color(color = 0xFF000000),
        onErrorContainer = Color(color = 0xFFFFFFFF),
        background = Color(color = 0xFFFFFFFF),
        onBackground = Color(color = 0xFF000000),
        surface = Color(color = 0xFFFFFFFF),
        onSurface = Color(color = 0xFF000000),
        surfaceVariant = Color(color = 0xFFFFFFFF),
        onSurfaceVariant = Color(color = 0xFF000000),
        outline = Color(color = 0xFF000000),
        outlineVariant = Color(color = 0xFF000000),
        scrim = Color(color = 0xFF000000),
        inverseSurface = Color(color = 0xFF000000),
        inverseOnSurface = Color(color = 0xFFFFFFFF),
        inversePrimary = Color(color = 0xFFFFFFFF),
        surfaceDim = Color(color = 0xFFFFFFFF),
        surfaceBright = Color(color = 0xFFFFFFFF),
        surfaceContainerLowest = Color(color = 0xFFFFFFFF),
        surfaceContainerLow = Color(color = 0xFFFFFFFF),
        surfaceContainer = Color(color = 0xFFFFFFFF),
        surfaceContainerHigh = Color(color = 0xFFFFFFFF),
        surfaceContainerHighest = Color(color = 0xFFFFFFFF),
    )
}
