package eu.kanade.presentation.theme.colorscheme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

/**
 * Colors for Strawberry Daiquiri theme
 * Original color scheme by Soitora
 * M3 color scheme generated by Material Theme Builder (https://goo.gle/material-theme-builder-web)
 *
 * Key colors:
 * Primary #ED4A65
 * Secondary #ED4A65
 * Tertiary #775930
 * Neutral #655C5C
 */
internal object StrawberryColorScheme : BaseColorScheme() {

    override val darkScheme = darkColorScheme(
        primary = Color(color = 0xFFFFB2B8),
        onPrimary = Color(color = 0xFF67001D),
        primaryContainer = Color(color = 0xFFD53855),
        onPrimaryContainer = Color(color = 0xFFFFFFFF),
        secondary = Color(color = 0xFFED4A65), // Unread badge
        onSecondary = Color(color = 0xFF201A1A), // Unread badge text
        secondaryContainer = Color(color = 0xFF91002A), // Navigation bar selector pill & progress indicator (remaining)
        onSecondaryContainer = Color(color = 0xFFFFFFFF), // Navigation bar selector icon
        tertiary = Color(color = 0xFFE8C08E), // Downloaded badge
        onTertiary = Color(color = 0xFF201A1A), // Downloaded badge text
        tertiaryContainer = Color(color = 0xFF775930),
        onTertiaryContainer = Color(color = 0xFFFFF7F1),
        error = Color(color = 0xFFFFB4AB),
        onError = Color(color = 0xFF690005),
        errorContainer = Color(color = 0xFF93000A),
        onErrorContainer = Color(color = 0xFFFFDAD6),
        background = Color(color = 0xFF201A1A),
        onBackground = Color(color = 0xFFF7DCDD),
        surface = Color(color = 0xFF201A1A),
        onSurface = Color(color = 0xFFF7DCDD),
        surfaceVariant = Color(color = 0xFF322727), // Navigation bar background (ThemePrefWidget)
        onSurfaceVariant = Color(color = 0xFFE1BEC0),
        outline = Color(color = 0xFFA9898B),
        outlineVariant = Color(color = 0xFF594042),
        scrim = Color(color = 0xFF000000),
        inverseSurface = Color(color = 0xFFF7DCDD),
        inverseOnSurface = Color(color = 0xFF3D2C2D),
        inversePrimary = Color(color = 0xFFB61F40),
        surfaceDim = Color(color = 0xFF1D1011),
        surfaceBright = Color(color = 0xFF463536),
        surfaceContainerLowest = Color(color = 0xFF2C2222),
        surfaceContainerLow = Color(color = 0xFF302525),
        surfaceContainer = Color(color = 0xFF322727), // Navigation bar background
        surfaceContainerHigh = Color(color = 0xFF3C2F2F),
        surfaceContainerHighest = Color(color = 0xFF463737),
    )

    override val lightScheme = lightColorScheme(
        primary = Color(color = 0xFFA10833),
        onPrimary = Color(color = 0xFFFFFFFF),
        primaryContainer = Color(color = 0xFFD53855),
        onPrimaryContainer = Color(color = 0xFFFFFFFF),
        secondary = Color(color = 0xFFA10833), // Unread badge
        onSecondary = Color(color = 0xFFFFFFFF), // Unread badge text
        secondaryContainer = Color(color = 0xFFD53855), // Navigation bar selector pill & progress indicator (remaining)
        onSecondaryContainer = Color(color = 0xFFF6EAED), // Navigation bar selector icon
        tertiary = Color(color = 0xFF5F441D), // Downloaded badge
        onTertiary = Color(color = 0xFFFFFFFF), // Downloaded badge text
        tertiaryContainer = Color(color = 0xFF87683D),
        onTertiaryContainer = Color(color = 0xFFFFFFFF),
        error = Color(color = 0xFFBA1A1A),
        onError = Color(color = 0xFFFFFFFF),
        errorContainer = Color(color = 0xFFFFDAD6),
        onErrorContainer = Color(color = 0xFF410002),
        background = Color(color = 0xFFFAFAFA),
        onBackground = Color(color = 0xFF261819),
        surface = Color(color = 0xFFFAFAFA),
        onSurface = Color(color = 0xFF261819),
        surfaceVariant = Color(color = 0xFFF6EAED), // Navigation bar background (ThemePrefWidget)
        onSurfaceVariant = Color(color = 0xFF594042),
        outline = Color(color = 0xFF8D7071),
        outlineVariant = Color(color = 0xFFE1BEC0),
        scrim = Color(color = 0xFF000000),
        inverseSurface = Color(color = 0xFF3D2C2D),
        inverseOnSurface = Color(color = 0xFFFFECED),
        inversePrimary = Color(color = 0xFFFFB2B8),
        surfaceDim = Color(color = 0xFFEED4D5),
        surfaceBright = Color(color = 0xFFFFF8F7),
        surfaceContainerLowest = Color(color = 0xFFF7DCDD),
        surfaceContainerLow = Color(color = 0xFFFDE2E3),
        surfaceContainer = Color(color = 0xFFF6EAED), // Navigation bar background
        surfaceContainerHigh = Color(color = 0xFFFFF0F0),
        surfaceContainerHighest = Color(color = 0xFFFFFFFF),
    )
}
