package eu.kanade.presentation.theme.colorscheme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

/**
 * Colors for Default theme
 * M3 colors generated by Material Theme Builder (https://goo.gle/material-theme-builder-web)
 *
 * Key colors:
 * Primary #2979FF
 * Secondary #2979FF
 * Tertiary #47A84A
 * Neutral #919094
 */
internal object TachiyomiColorScheme : BaseColorScheme() {

    override val darkScheme = darkColorScheme(
        primary = Color(color = 0xFFB0C6FF),
        onPrimary = Color(color = 0xFF002D6E),
        primaryContainer = Color(color = 0xFF00429B),
        onPrimaryContainer = Color(color = 0xFFD9E2FF),
        inversePrimary = Color(color = 0xFF0058CA),
        secondary = Color(color = 0xFFB0C6FF), // Unread badge
        onSecondary = Color(color = 0xFF002D6E), // Unread badge text
        secondaryContainer = Color(color = 0xFF00429B), // Navigation bar selector pill & pro
        onSecondaryContainer = Color(color = 0xFFD9E2FF), // Navigation bar selector icon
        tertiary = Color(color = 0xFF7ADC77), // Downloaded badge
        onTertiary = Color(color = 0xFF003909), // Downloaded badge text
        tertiaryContainer = Color(color = 0xFF005312),
        onTertiaryContainer = Color(color = 0xFF95F990),
        background = Color(color = 0xFF1B1B1F),
        onBackground = Color(color = 0xFFE3E2E6),
        surface = Color(color = 0xFF1B1B1F),
        onSurface = Color(color = 0xFFE3E2E6),
        surfaceVariant = Color(color = 0xFF211F26), // Navigation bar background (ThemePrefWidget)
        onSurfaceVariant = Color(color = 0xFFC5C6D0),
        surfaceTint = Color(color = 0xFFB0C6FF),
        inverseSurface = Color(color = 0xFFE3E2E6),
        inverseOnSurface = Color(color = 0xFF1B1B1F),
        error = Color(color = 0xFFFFB4AB),
        onError = Color(color = 0xFF690005),
        errorContainer = Color(color = 0xFF93000A),
        onErrorContainer = Color(color = 0xFFFFDAD6),
        outline = Color(color = 0xFF8F9099),
        outlineVariant = Color(color = 0xFF44464F),
        surfaceContainerLowest = Color(color = 0xFF1A181D),
        surfaceContainerLow = Color(color = 0xFF1E1C22),
        surfaceContainer = Color(color = 0xFF211F26), // Navigation bar background
        surfaceContainerHigh = Color(color = 0xFF292730),
        surfaceContainerHighest = Color(color = 0xFF302E38),
    )

    override val lightScheme = lightColorScheme(
        primary = Color(color = 0xFF0058CA),
        onPrimary = Color(color = 0xFFFFFFFF),
        primaryContainer = Color(color = 0xFFD9E2FF),
        onPrimaryContainer = Color(color = 0xFF001945),
        inversePrimary = Color(color = 0xFFB0C6FF),
        secondary = Color(color = 0xFF0058CA), // Unread badge
        onSecondary = Color(color = 0xFFFFFFFF), // Unread badge text
        secondaryContainer = Color(color = 0xFFD9E2FF), // Navigation bar selector pill & progress indicator (remaining)
        onSecondaryContainer = Color(color = 0xFF001945), // Navigation bar selector icon
        tertiary = Color(color = 0xFF006E1B), // Downloaded badge
        onTertiary = Color(color = 0xFFFFFFFF), // Downloaded badge text
        tertiaryContainer = Color(color = 0xFF95F990),
        onTertiaryContainer = Color(color = 0xFF002203),
        background = Color(color = 0xFFFEFBFF),
        onBackground = Color(color = 0xFF1B1B1F),
        surface = Color(color = 0xFFFEFBFF),
        onSurface = Color(color = 0xFF1B1B1F),
        surfaceVariant = Color(color = 0xFFF3EDF7), // Navigation bar background (ThemePrefWidget)
        onSurfaceVariant = Color(color = 0xFF44464F),
        surfaceTint = Color(color = 0xFF0058CA),
        inverseSurface = Color(color = 0xFF303034),
        inverseOnSurface = Color(color = 0xFFF2F0F4),
        error = Color(color = 0xFFBA1A1A),
        onError = Color(color = 0xFFFFFFFF),
        errorContainer = Color(color = 0xFFFFDAD6),
        onErrorContainer = Color(color = 0xFF410002),
        outline = Color(color = 0xFF757780),
        outlineVariant = Color(color = 0xFFC5C6D0),
        surfaceContainerLowest = Color(color = 0xFFF5F1F8),
        surfaceContainerLow = Color(color = 0xFFF7F2FA),
        surfaceContainer = Color(color = 0xFFF3EDF7), // Navigation bar background
        surfaceContainerHigh = Color(color = 0xFFFCF7FF),
        surfaceContainerHighest = Color(color = 0xFFFCF7FF),
    )
}
