package eu.kanade.presentation.theme.colorscheme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

/**
 * Colors for Tako theme
 * Original color scheme by ghostbear
 * M3 color scheme generated by Material Theme Builder (https://goo.gle/material-theme-builder-web).
 *
 * Key colors:
 * Primary #F3B375
 * Secondary #F3B375
 * Tertiary #66577E
 * Neutral #21212E
 */
internal object TakoColorScheme : BaseColorScheme() {

    override val darkScheme = darkColorScheme(
        primary = Color(color = 0xFFF3B375),
        onPrimary = Color(color = 0xFF38294E),
        primaryContainer = Color(color = 0xFFF3B375),
        onPrimaryContainer = Color(color = 0xFF38294E),
        inversePrimary = Color(color = 0xFF84531E),
        secondary = Color(color = 0xFFF3B375), // Unread badge
        onSecondary = Color(color = 0xFF38294E), // Unread badge text
        secondaryContainer = Color(color = 0xFF5C4D4B), // Navigation bar selector pill & progress indicator (remaining)
        onSecondaryContainer = Color(color = 0xFFF3B375), // Navigation bar selector icon
        tertiary = Color(color = 0xFF66577E), // Downloaded badge
        onTertiary = Color(color = 0xFFF3B375), // Downloaded badge text
        tertiaryContainer = Color(color = 0xFF4E4065),
        onTertiaryContainer = Color(color = 0xFFEDDCFF),
        background = Color(color = 0xFF21212E),
        onBackground = Color(color = 0xFFE3E0F2),
        surface = Color(color = 0xFF21212E),
        onSurface = Color(color = 0xFFE3E0F2),
        surfaceVariant = Color(color = 0xFF2A2A3C), // Navigation bar background (ThemePrefWidget)
        onSurfaceVariant = Color(color = 0xFFCBC4CE),
        surfaceTint = Color(color = 0xFF66577E),
        inverseSurface = Color(color = 0xFFE5E1E6),
        inverseOnSurface = Color(color = 0xFF1B1B1E),
        outline = Color(color = 0xFF958F99),
        surfaceContainerLowest = Color(color = 0xFF20202E),
        surfaceContainerLow = Color(color = 0xFF262636),
        surfaceContainer = Color(color = 0xFF2A2A3C), // Navigation bar background
        surfaceContainerHigh = Color(color = 0xFF303044),
        surfaceContainerHighest = Color(color = 0xFF36364D),
    )

    override val lightScheme = lightColorScheme(
        primary = Color(color = 0xFF66577E),
        onPrimary = Color(color = 0xFFF3B375),
        primaryContainer = Color(color = 0xFF66577E),
        onPrimaryContainer = Color(color = 0xFFF3B375),
        inversePrimary = Color(color = 0xFFD6BAFF),
        secondary = Color(color = 0xFF66577E), // Unread badge
        onSecondary = Color(color = 0xFFF3B375), // Unread badge text
        secondaryContainer = Color(color = 0xFFC8BED0), // Navigation bar selector pill & progress indicator (remaining)
        onSecondaryContainer = Color(color = 0xFF66577E), // Navigation bar selector icon
        tertiary = Color(color = 0xFFF3B375), // Downloaded badge
        onTertiary = Color(color = 0xFF574360), // Downloaded badge text
        tertiaryContainer = Color(color = 0xFFFDD6B0),
        onTertiaryContainer = Color(color = 0xFF221437),
        background = Color(color = 0xFFF7F5FF),
        onBackground = Color(color = 0xFF1B1B22),
        surface = Color(color = 0xFFF7F5FF),
        onSurface = Color(color = 0xFF1B1B22),
        surfaceVariant = Color(color = 0xFFE8E0EB), // Navigation bar background (ThemePrefWidget)
        onSurfaceVariant = Color(color = 0xFF49454E),
        surfaceTint = Color(color = 0xFF66577E),
        inverseSurface = Color(color = 0xFF313033),
        inverseOnSurface = Color(color = 0xFFF3EFF4),
        outline = Color(color = 0xFF7A757E),
        surfaceContainerLowest = Color(color = 0xFFD7D0DA),
        surfaceContainerLow = Color(color = 0xFFDFD8E2),
        surfaceContainer = Color(color = 0xFFE8E0EB), // Navigation bar background
        surfaceContainerHigh = Color(color = 0xFFEEE6F1),
        surfaceContainerHighest = Color(color = 0xFFF7EEFA),
    )
}
