package eu.kanade.presentation.theme.colorscheme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

/**
 * Colors for Yin & Yang theme
 * Original color scheme by Riztard
 * M3 colors generated by yours truly + tweaked manually.
 */
internal object YinYangColorScheme : BaseColorScheme() {

    override val darkScheme = darkColorScheme(
        primary = Color(color = 0xFFFFFFFF),
        onPrimary = Color(color = 0xFF5A5A5A),
        primaryContainer = Color(color = 0xFFFFFFFF),
        onPrimaryContainer = Color(color = 0xFF000000),
        inversePrimary = Color(color = 0xFFCECECE),
        secondary = Color(color = 0xFFFFFFFF), // Unread badge
        onSecondary = Color(color = 0xFF5A5A5A), // Unread badge text
        secondaryContainer = Color(color = 0xFF717171), // Navigation bar selector pill & progress indicator (remaining)
        onSecondaryContainer = Color(color = 0xFFE4E4E4), // Navigation bar selector icon
        tertiary = Color(color = 0xFF000000), // Downloaded badge
        onTertiary = Color(color = 0xFFFFFFFF), // Downloaded badge text
        tertiaryContainer = Color(color = 0xFF00419E),
        onTertiaryContainer = Color(color = 0xFFD8E2FF),
        background = Color(color = 0xFF1E1E1E),
        onBackground = Color(color = 0xFFE6E6E6),
        surface = Color(color = 0xFF1E1E1E),
        onSurface = Color(color = 0xFFE6E6E6),
        surfaceVariant = Color(color = 0xFF313131), // Navigation bar background (ThemePrefWidget)
        onSurfaceVariant = Color(color = 0xFFD1D1D1),
        surfaceTint = Color(color = 0xFFFFFFFF),
        inverseSurface = Color(color = 0xFFE6E6E6),
        inverseOnSurface = Color(color = 0xFF1E1E1E),
        outline = Color(color = 0xFF999999),
        surfaceContainerLowest = Color(color = 0xFF2A2A2A),
        surfaceContainerLow = Color(color = 0xFF2D2D2D),
        surfaceContainer = Color(color = 0xFF313131), // Navigation bar background
        surfaceContainerHigh = Color(color = 0xFF383838),
        surfaceContainerHighest = Color(color = 0xFF3F3F3F),
    )

    override val lightScheme = lightColorScheme(
        primary = Color(color = 0xFF000000),
        onPrimary = Color(color = 0xFFFFFFFF),
        primaryContainer = Color(color = 0xFF000000),
        onPrimaryContainer = Color(color = 0xFFFFFFFF),
        inversePrimary = Color(color = 0xFFA6A6A6),
        secondary = Color(color = 0xFF000000), // Unread badge
        onSecondary = Color(color = 0xFFFFFFFF), // Unread badge text
        secondaryContainer = Color(color = 0xFFDDDDDD), // Navigation bar selector pill & progress indicator (remaining)
        onSecondaryContainer = Color(color = 0xFF0C0C0C), // Navigation bar selector icon
        tertiary = Color(color = 0xFFFFFFFF), // Downloaded badge
        onTertiary = Color(color = 0xFF000000), // Downloaded badge text
        tertiaryContainer = Color(color = 0xFFD8E2FF),
        onTertiaryContainer = Color(color = 0xFF001947),
        background = Color(color = 0xFFFDFDFD),
        onBackground = Color(color = 0xFF222222),
        surface = Color(color = 0xFFFDFDFD),
        onSurface = Color(color = 0xFF222222),
        surfaceVariant = Color(color = 0xFFE8E8E8), // Navigation bar background (ThemePrefWidget)
        onSurfaceVariant = Color(color = 0xFF515151),
        surfaceTint = Color(color = 0xFF000000),
        inverseSurface = Color(color = 0xFF333333),
        inverseOnSurface = Color(color = 0xFFF4F4F4),
        outline = Color(color = 0xFF838383),
        surfaceContainerLowest = Color(color = 0xFFCFCFCF),
        surfaceContainerLow = Color(color = 0xFFDADADA),
        surfaceContainer = Color(color = 0xFFE8E8E8), // Navigation bar background
        surfaceContainerHigh = Color(color = 0xFFECECEC),
        surfaceContainerHighest = Color(color = 0xFFEFEFEF),
    )
}
