package eu.kanade.presentation.theme.colorscheme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

/**
 * Colors for Yotsuba theme
 * Original color scheme by ztimms73
 * M3 colors generated by Material Theme Builder (https://goo.gle/material-theme-builder-web).
 *
 * Key colors:
 * Primary 0xFFAE3200
 * Secondary 0xFFAE3200
 * Tertiary 0xFF6B5E2F
 * Neutral 0xFF655C5A
 */
internal object YotsubaColorScheme : BaseColorScheme() {

    override val darkScheme = darkColorScheme(
        primary = Color(color = 0xFFFFB59D),
        onPrimary = Color(color = 0xFF5F1600),
        primaryContainer = Color(color = 0xFF862200),
        onPrimaryContainer = Color(color = 0xFFFFDBCF),
        inversePrimary = Color(color = 0xFFAE3200),
        secondary = Color(color = 0xFFFFB59D), // Unread badge
        onSecondary = Color(color = 0xFF5F1600), // Unread badge text
        secondaryContainer = Color(color = 0xFF862200), // Navigation bar selector pill & progress indicator (remaining)
        onSecondaryContainer = Color(color = 0xFFFFDBCF), // Navigation bar selector icon
        tertiary = Color(color = 0xFFD7C68D), // Downloaded badge
        onTertiary = Color(color = 0xFF3A2F05), // Downloaded badge text
        tertiaryContainer = Color(color = 0xFF524619),
        onTertiaryContainer = Color(color = 0xFFF5E2A7),
        background = Color(color = 0xFF211A18),
        onBackground = Color(color = 0xFFEDE0DD),
        surface = Color(color = 0xFF211A18),
        onSurface = Color(color = 0xFFEDE0DD),
        surfaceVariant = Color(color = 0xFF332723), // Navigation bar background (ThemePrefWidget)
        onSurfaceVariant = Color(color = 0xFFD8C2BC),
        surfaceTint = Color(color = 0xFFFFB59D),
        inverseSurface = Color(color = 0xFFEDE0DD),
        inverseOnSurface = Color(color = 0xFF211A18),
        outline = Color(color = 0xFFA08C87),
        surfaceContainerLowest = Color(color = 0xFF2E221F),
        surfaceContainerLow = Color(color = 0xFF312521),
        surfaceContainer = Color(color = 0xFF332723), // Navigation bar background
        surfaceContainerHigh = Color(color = 0xFF413531),
        surfaceContainerHighest = Color(color = 0xFF4C403D),
    )

    override val lightScheme = lightColorScheme(
        primary = Color(color = 0xFFAE3200),
        onPrimary = Color(color = 0xFFFFFFFF),
        primaryContainer = Color(color = 0xFFFFDBCF),
        onPrimaryContainer = Color(color = 0xFF3B0A00),
        inversePrimary = Color(color = 0xFFFFB59D),
        secondary = Color(color = 0xFFAE3200), // Unread badge
        onSecondary = Color(color = 0xFFFFFFFF), // Unread badge text
        secondaryContainer = Color(color = 0xFFEBCDC2), // Navigation bar selector pill & progress indicator (remaining)
        onSecondaryContainer = Color(color = 0xFF3B0A00), // Navigation bar selector icon
        tertiary = Color(color = 0xFF6B5E2F), // Downloaded badge
        onTertiary = Color(color = 0xFFFFFFFF), // Downloaded badge text
        tertiaryContainer = Color(color = 0xFFF5E2A7),
        onTertiaryContainer = Color(color = 0xFF231B00),
        background = Color(color = 0xFFFCFCFC),
        onBackground = Color(color = 0xFF211A18),
        surface = Color(color = 0xFFFCFCFC),
        onSurface = Color(color = 0xFF211A18),
        surfaceVariant = Color(color = 0xFFF6EBE7), // Navigation bar background (ThemePrefWidget)
        onSurfaceVariant = Color(color = 0xFF53433F),
        surfaceTint = Color(color = 0xFFAE3200),
        inverseSurface = Color(color = 0xFF362F2D),
        inverseOnSurface = Color(color = 0xFFFBEEEB),
        outline = Color(color = 0xFF85736E),
        surfaceContainerLowest = Color(color = 0xFFECE3E0),
        surfaceContainerLow = Color(color = 0xFFF1E7E4),
        surfaceContainer = Color(color = 0xFFF6EBE7), // Navigation bar background
        surfaceContainerHigh = Color(color = 0xFFFAF4F2),
        surfaceContainerHighest = Color(color = 0xFFFBF6F4),
    )
}
